name: Test Output Input

on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    strategy:
      matrix:
        stage: [ 'dev', 'uat' ]
    uses: .github/workflows/output-input-workflow.yaml@14397ab752ebb240a2c942953846496b87959d9e
    with:
      environment: ${{ matrix.stage }}
      value-overrides: |
        env=${{ matrix.stage }}
        fruit=${{ vars.fruit }}

