name: Test Output Input

on:
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage: [ 'dev', 'uat' ]
    environment: ${{ matrix.stage }}
    steps:
      - run: echo "${{ vars.FRUIT }}"
  vars:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage: [ 'dev', 'uat' ]
    environment: ${{ matrix.stage }}
    steps:
      - run: echo "Setting environment variables... ${{ vars.FRUIT }}"
      - run: |
          echo "${{ matrix.stage }}_FRUIT=${{ vars.FRUIT }}" >> $GITHUB_OUTPUT
  test:
    needs: [ check, vars ]
    name: Test
    strategy:
      matrix:
        stage: [ 'dev', 'uat' ]
    uses: ./.github/workflows/output-input.yaml
    with:
      environment: ${{ matrix.stage }}
      value-overrides: |
        env=${{ matrix.stage }}
        fruit=${{ vars.FRUIT }}
        fruit2=${{ needs.vars.outputs[format('{0}_FRUIT', matrix.stage)] }}
