name: Test Output Input

on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    strategy:
      matrix:
        stage: [ 'dev', 'uat' ]
    uses: ./.github/workflows/output-input.yaml
    with:
      environment: ${{ matrix.stage }}
      value-overrides: |
        env=${{ matrix.stage }}
        fruit=${{ vars.fruit }}

